"""add_phase1_tables

Revision ID: 60ae9c80bdbe
Revises: ae4b7526e06a
Create Date: 2026-08-16 13:27:59.885986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ae9c80bdbe'
down_revision: Union[str, None] = 'ae4b7526e06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('solver', sa.String(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_started_at', 'pipeline_runs', ['started_at'], unique=False)
    op.create_index('ix_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_unresolved', 'alerts', ['resolved', 'severity'], unique=False)
    op.create_table('demand_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_run_loc_prod', 'demand_forecast', ['pipeline_run_id', 'location_id', 'product_id'], unique=False)
    op.create_table('demand_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'product_id', 'date', name='uq_demand_loc_prod_date')
    )
    op.create_index('ix_demand_history_date', 'demand_history', ['date'], unique=False)
    op.create_index('ix_demand_history_loc_prod', 'demand_history', ['location_id', 'product_id'], unique=False)
    op.create_table('lanes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('transit_time', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uq_lane_src_tgt')
    )
    op.create_index('ix_lanes_source', 'lanes', ['source_id'], unique=False)
    op.create_index('ix_lanes_target', 'lanes', ['target_id'], unique=False)
    op.create_table('location_product_policy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('service_level', sa.Float(), nullable=True),
    sa.Column('max_s_out', sa.Integer(), nullable=True),
    sa.Column('min_s_out', sa.Integer(), nullable=True),
    sa.Column('holding_cost', sa.Float(), nullable=True),
    sa.Column('ordering_cost', sa.Float(), nullable=True),
    sa.Column('review_period', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'product_id', name='uq_policy_loc_prod')
    )
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('s_in', sa.Integer(), nullable=True),
    sa.Column('s_out', sa.Integer(), nullable=True),
    sa.Column('net_replenishment_time', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Float(), nullable=True),
    sa.Column('order_quantity', sa.Float(), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_results_loc_prod', 'optimization_results', ['location_id', 'product_id'], unique=False)
    op.create_index('ix_opt_results_run', 'optimization_results', ['pipeline_run_id'], unique=False)
    op.create_table('lead_time_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lane_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(), nullable=False),
    sa.Column('planned_lt', sa.Integer(), nullable=True),
    sa.Column('actual_lt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lt_obs_lane', 'lead_time_observations', ['lane_id'], unique=False)
    op.add_column('inventory_snapshot', sa.Column('snapshot_date', sa.DateTime(), nullable=False))
    op.add_column('inventory_snapshot', sa.Column('on_order', sa.Float(), nullable=True))
    op.add_column('inventory_snapshot', sa.Column('in_transit', sa.Float(), nullable=True))
    op.create_index('ix_inv_snapshot_loc_prod', 'inventory_snapshot', ['location_id', 'product_id'], unique=False)
    op.create_unique_constraint('uq_inv_snapshot', 'inventory_snapshot', ['location_id', 'product_id', 'snapshot_date'])
    op.add_column('locations', sa.Column('region', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_locations_type', 'locations', ['type'], unique=False)
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit_cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_unique_constraint(None, 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'unit_cost')
    op.drop_column('products', 'sku')
    op.drop_index('ix_locations_type', table_name='locations')
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'region')
    op.drop_constraint('uq_inv_snapshot', 'inventory_snapshot', type_='unique')
    op.drop_index('ix_inv_snapshot_loc_prod', table_name='inventory_snapshot')
    op.drop_column('inventory_snapshot', 'in_transit')
    op.drop_column('inventory_snapshot', 'on_order')
    op.drop_column('inventory_snapshot', 'snapshot_date')
    op.drop_index('ix_lt_obs_lane', table_name='lead_time_observations')
    op.drop_table('lead_time_observations')
    op.drop_index('ix_opt_results_run', table_name='optimization_results')
    op.drop_index('ix_opt_results_loc_prod', table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_table('location_product_policy')
    op.drop_index('ix_lanes_target', table_name='lanes')
    op.drop_index('ix_lanes_source', table_name='lanes')
    op.drop_table('lanes')
    op.drop_index('ix_demand_history_loc_prod', table_name='demand_history')
    op.drop_index('ix_demand_history_date', table_name='demand_history')
    op.drop_table('demand_history')
    op.drop_index('ix_forecast_run_loc_prod', table_name='demand_forecast')
    op.drop_table('demand_forecast')
    op.drop_index('ix_alerts_unresolved', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_started_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
